import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import LayoutWithoutSSR from "@/without-ssr/layout";

const Roboto = localFont({
  src: "../../public/assets/fonts/Roboto-Regular.ttf",
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={Roboto.variable}>
      <body>
        <LayoutWithoutSSR>
          <div>{children}</div>
        </LayoutWithoutSSR>
      </body>
    </html>
  );
}
